---
abstract: 'Pluggable library handles many databases a.k.a Database Sharding.'
author:
  - 'Kosuke Arisawa <arisawa@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Sharding
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Class::Data::Inheritable: 0
  DBI: 0
  UNIVERSAL::require: 0
  YAML: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
